support ubuntu
adds support for ubuntu 16 and 14

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,28 +9,44 @@ env:
   - distro: centos6
     init: /sbin/init
     run_opts: ""
+  - distro: ubuntu1604
+    init: /lib/systemd/systemd
+    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
+  - distro: ubuntu1404
+    init: /sbin/init
+    run_opts: ""
 
 before_install:
-  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'
+  - 'docker pull geerlingguy/docker-$distro-ansible:latest'
 
 script:
   - container_id=$(mktemp)
 
-  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/repo-xcat:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
+  - 'docker run --detach --volume="$PWD":/etc/ansible/roles/repo-xcat:ro $run_opts geerlingguy/docker-$distro-ansible:latest "$init" > "$container_id"'
 
-  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/repo-xcat/tests/test.yml --syntax-check'
+  - 'docker exec --tty "$(cat $container_id)" env TERM=xterm ansible localhost -m setup'
 
-  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/repo-xcat/tests/test.yml'
+  - 'docker exec --tty "$(cat $container_id)" env TERM=xterm ansible-playbook /etc/ansible/roles/repo-xcat/tests/test.yml --syntax-check'
+
+  - 'docker exec "$(cat $container_id)" ansible-playbook /etc/ansible/roles/repo-xcat/tests/test.yml'
 
   - idempotence=$(mktemp)
-  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/repo-xcat/tests/test.yml | tee -a ${idempotence}
+  - docker exec "$(cat $container_id)" ansible-playbook /etc/ansible/roles/repo-xcat/tests/test.yml | tee -a $idempotence
   - >
-    tail ${idempotence}
+    tail $idempotence
     | grep -q 'changed=0.*failed=0'
-    && (echo 'Idempotence test: pass' && exit 0)
-    || (echo 'Idempotence test: fail' && exit 1)
+    && (echo 'idempotence test: pass' && exit 0)
+    || (echo 'idempotence test: fail' && exit 1)
 
-  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm yum -y install xCAT'
+  - |
+    if [[ $distro =~ "centos" ]] ; then
+      docker exec $(cat $container_id) yum -y install xCAT
+    fi
+  - |
+    if [[ $distro =~ "ubuntu" ]] ; then
+      docker exec $(cat $container_id) apt-get update
+      docker exec $(cat $container_id) apt-get install -y xcat
+    fi
 
 notifications:
   webhooks: https://galaxy.ansible.com/api/v1/notifications/
